---
- name: Setup mitigations
  hosts: all
  become: true
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        update_cache: true
        name:
          - selinux-basics
          - selinux-policy-default
          - auditd

    - name: Disable AppArmor
      ansible.builtin.service:
        name: apparmor
        state: stopped
        enabled: false

    - name: Enable SELinux
      ansible.builtin.command:
        cmd: selinux-activate
      changed_when: true

    - name: Reboot
      ansible.builtin.reboot:

    - name: Check SELinux installation
      ansible.builtin.command:
        cmd: check-selinux-installation
      changed_when: false

    - name: Set systemd-networkd to permissive
      ansible.builtin.command:
        cmd: semanage permissive -a systemd_networkd_t
      changed_when: true

    - name: Create vagrant SSH keypair
      become: true
      become_user: vagrant
      ansible.builtin.command:
        cmd: ssh-keygen -t ed25519 -N "" -f ~/.ssh/id_ed25519
        creates: ~/.ssh/id_ed25519

    - name: Create .ssh directory for john
      ansible.builtin.file:
        path: /home/john/.ssh
        state: directory
        owner: john
        group: john
        mode: "0700"

    - name: Allow vagrant to ssh into john
      ansible.builtin.copy:
        src: /home/vagrant/.ssh/id_ed25519.pub
        remote_src: true
        dest: /home/john/.ssh/authorized_keys
        owner: john
        group: john
        mode: "0600"

    - name: Map john to user_u
      ansible.builtin.command:
        cmd: semanage login -a -s user_u john
      changed_when: true

    - name: Relabel john home directory
      ansible.builtin.command:
        cmd: restorecon -RF /home/john
      changed_when: true

    - name: Copy policy source
      ansible.builtin.copy:
        src: policy.te
        dest: ~/policy.te
        mode: preserve

    - name: Build policy
      ansible.builtin.command:
        cmd: make -f /usr/share/selinux/devel/Makefile
        chdir: ~/
      changed_when: true

    - name: Install policy
      ansible.builtin.command:
        cmd: semodule -i ~/policy.pp
      changed_when: true

    - name: Enforce SELinux
      ansible.builtin.lineinfile:
        path: /etc/selinux/config
        regexp: "^SELINUX="
        line: SELINUX=enforcing

    - name: Reboot
      ansible.builtin.reboot:
