---
- name: Setup mitigations
  hosts: all
  become: true
  tasks:
    - name: Disable AppArmor
      ansible.builtin.systemd_service:
        name: apparmor
        state: stopped
        masked: true

    - name: Enable LSM BPF
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: "^GRUB_CMDLINE_LINUX="
        line: GRUB_CMDLINE_LINUX="lsm=lockdown,capability,landlock,yama,bpf"
      notify:
        - Update GRUB
        - Reboot

    - name: Install apt packages
      ansible.builtin.apt:
        update_cache: true
        name:
          - libbpf-dev
          - clang
          - pkg-config
          - python3-pip

    - name: Install bpftool
      ansible.builtin.unarchive:
        src: https://github.com/libbpf/bpftool/releases/download/v7.3.0/bpftool-v7.3.0-amd64.tar.gz
        remote_src: true
        dest: /usr/local/bin
        mode: "0755"
        creates: /usr/local/bin/bpftool

    - name: Install meson
      ansible.builtin.pip:
        name:
          - meson
          - ninja

    - name: Copy lsm_bpf sources
      ansible.builtin.copy:
        src: lsm_bpf/
        dest: /usr/src/lsm_bpf
        mode: "0755"
      notify: Recompile lsm_bpf

  handlers:
    - name: Update GRUB
      ansible.builtin.command:
        cmd: update-grub
      changed_when: true

    - name: Reboot
      ansible.builtin.reboot:
        reboot_command: systemctl reboot

    - name: Recompile lsm_bpf
      environment:
        CC: clang
      ansible.builtin.shell:
        cmd: |
          meson setup build --wipe
          meson compile -C build
          meson install -C build
        chdir: /usr/src/lsm_bpf
      changed_when: true
