---
- name: Setup mitigations
  hosts: all
  become: true
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        update_cache: true
        name:
          - selinux-basics
          - selinux-policy-default
          - auditd
      notify:
        - Enable SELinux

    - name: Disable AppArmor
      ansible.builtin.systemd_service:
        name: apparmor
        state: stopped
        masked: true

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Set system components to permissive
      community.general.selinux_permissive:
        name: "{{ item }}"
        permissive: true
      with_items:
        - systemd_networkd_t
        - systemd_resolved_t

    - name: Create vagrant SSH keypair
      become: true
      become_user: vagrant
      community.crypto.openssh_keypair:
        path: /home/vagrant/.ssh/id_rsa
      register: vagrant_keypair

    - name: Allow vagrant to ssh into john
      ansible.posix.authorized_key:
        user: john
        key: "{{ vagrant_keypair.public_key }}"

    - name: Map john to user_u
      community.general.selogin:
        login: john
        seuser: user_u
      notify:
        - Relabel john home directory

    - name: Copy policy source
      ansible.builtin.copy:
        src: policy.te
        dest: /root/policy.te
        mode: preserve

    - name: Build policy
      community.general.make:
        chdir: /root
        target: policy.pp
        file: /usr/share/selinux/devel/Makefile
      notify:
        - Install policy

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Enforce SELinux
      ansible.builtin.lineinfile:
        path: /etc/selinux/config
        regexp: "^SELINUX="
        line: SELINUX=enforcing
      notify:
        - Reboot

  handlers:
    - name: Enable SELinux
      ansible.builtin.command:
        cmd: selinux-activate
      changed_when: true
      notify:
        - Reboot
        - Check SELinux installation

    - name: Reboot
      ansible.builtin.reboot:

    - name: Check SELinux installation
      ansible.builtin.command:
        cmd: check-selinux-installation
      changed_when: false

    - name: Relabel john home directory
      ansible.builtin.command:
        cmd: restorecon -RF /home/john
      changed_when: true

    - name: Install policy
      ansible.builtin.command:
        cmd: semodule -i /root/policy.pp
      changed_when: true
